### ISSUE TITLE
Pending changes to login and new post pages

### ISSUE THREAD

**Issue by broxmen** [broxmen/notif-octo#1]
Changes in color , styling need to be done in order to make it uniform with the main.html page. Also make the content stand out from the background.
Hex color codes
Blue color : #2196F3 (Navbar)
Grey color : #546E7A (Panel / Card)
Teal color : #26A69A (Secondary color / Accent)
Background Image: http://subtlepatterns2015.subtlepatterns.netdna-cdn.com/patterns/sayagata-400px.png
:+1:

**Comment by haramrit09k** [comment]
On it buddy!
