### ISSUE TITLE
Changes to be done

### ISSUE THREAD

**Issue by broxmen** [broxmen/notif-octo#2]
- Login page icons fix: 
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

- Main page back to text based logo "Logo" text

- Post page still contains the side bar from the main page

**Comment by haramrit09k** [comment]
Didn't understand what to do for the 1st and the 3rd one....2nd one is done, just check if it's satisfactory  @broxmen
